# Site settings
title: Mohamed Bassem
email: medoox240@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
#url: "http://mohamedbassem.github.io" # the base hostname & protocol for your site
twitter_username: MohamedBassem
github_username:  MohamedBassem
timezone: Africa/Cairo
destination: blog

# Build settings
markdown: kramdown
pygments: true
